// mobile/app/terms.tsx
import React from 'react';
import { View, Text, StyleSheet, ScrollView } from 'react-native';
import { WebHeader } from '../components/WebHeader';
import { WebFooter } from '../components/WebFooter';
import { Link } from 'expo-router';

export default function TermsOfServiceScreen() {
    return (
        <ScrollView style={styles.scrollScreen} contentContainerStyle={styles.scrollContent}>
            <WebHeader />

            <main style={{ width: '100%', display: 'flex', justifyContent: 'center' }}>
                <View style={styles.container}>
                    <View style={styles.content}>
                        <View style={styles.breadcrumb}>
                            <Link href="/" style={styles.breadcrumbLink}>Home</Link>
                            <Text style={styles.breadcrumbSeparator}>/</Text>
                            <Text style={styles.breadcrumbCurrent}>Terms of Service</Text>
                        </View>

                        <Text style={styles.title}>Terms of Service</Text>
                        <Text style={styles.lastUpdated}>Last Updated: September 10, 2026</Text>

                        <Text style={styles.lead}>
                            Please read these Terms of Service carefully before accessing or using the Sassy Magic 8-Ball website or mobile applications. By accessing our services, you agree to be bound by these terms.
                        </Text>

                        {/* SECTION 1 */}
                        <View style={styles.section}>
                            <Text style={styles.h2}>1. Entertainment &amp; Novelty Disclaimer</Text>
                            <View style={styles.alertBox}>
                                <Text style={styles.alertText}>
                                    <Text style={styles.bold}>IMPORTANT NOTICE: </Text>
                                    The Sassy Magic 8-Ball is an interactive entertainment novelty application. All fortunes, answers, roasts, and advice generated by the app are produced by computer algorithms and are intended strictly for comedic, satirical, and recreational purposes.
                                </Text>
                            </View>
                            <Text style={styles.paragraph}>
                                You expressly agree that you will NOT rely on the Sassy Magic 8-Ball for making medical, legal, financial, psychological, marital, career, or life-critical decisions. Always consult a licensed, qualified human professional for real-world advice.
                            </Text>
                        </View>

                        {/* SECTION 2 */}
                        <View style={styles.section}>
                            <Text style={styles.h2}>2. Acceptable Use Policy</Text>
                            <Text style={styles.paragraph}>
                                When utilizing our services, you agree not to:
                            </Text>
                            <Text style={styles.bulletItem}>
                                &bull; Launch denial-of-service (DDoS) attacks, flood our API endpoints, or disrupt server infrastructure.
                            </Text>
                            <Text style={styles.bulletItem}>
                                &bull; Use automated crawlers, bots, or scrapers to extract our fortune database without prior written consent.
                            </Text>
                            <Text style={styles.bulletItem}>
                                &bull; Attempt to decompile, reverse-engineer, or circumvent security features of the API or client application.
                            </Text>
                            <Text style={styles.bulletItem}>
                                &bull; Exploit, harass, or defame any individual using fortunes generated by this service.
                            </Text>
                        </View>

                        {/* SECTION 3 */}
                        <View style={styles.section}>
                            <Text style={styles.h2}>3. Intellectual Property</Text>
                            <Text style={styles.paragraph}>
                                All content, original fortune databases, code, branding, artwork, 3D die geometry, and styling are the intellectual property of Sassy Magic 8-Ball. You may share individual fortune screenshots and quotes on social media with appropriate attribution.
                            </Text>
                        </View>

                        {/* SECTION 4 */}
                        <View style={styles.section}>
                            <Text style={styles.h2}>4. Third-Party Advertisements &amp; Links</Text>
                            <Text style={styles.paragraph}>
                                Our website displays advertisements served by Google AdSense and third-party advertising partners. We do not endorse or assume responsibility for any third-party products, services, or websites advertised. Your interactions with advertisers are solely between you and the respective third party.
                            </Text>
                        </View>

                        {/* SECTION 5 */}
                        <View style={styles.section}>
                            <Text style={styles.h2}>5. Disclaimer of Warranties</Text>
                            <Text style={styles.paragraph}>
                                THE SERVICE IS PROVIDED ON AN &quot;AS IS&quot; AND &quot;AS AVAILABLE&quot; BASIS WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED. WE DO NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED, BUG-FREE, OR ACCURATE IN PREDICTING FUTURE EVENTS.
                            </Text>
                        </View>

                        {/* SECTION 6 */}
                        <View style={styles.section}>
                            <Text style={styles.h2}>6. Limitation of Liability</Text>
                            <Text style={styles.paragraph}>
                                TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL THE CREATORS, DEVELOPERS, OR AFFILIATES OF SASSY MAGIC 8-BALL BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES ARISING FROM YOUR USE OF OR INABILITY TO USE THE SERVICE.
                            </Text>
                        </View>

                        {/* SECTION 7 */}
                        <View style={styles.section}>
                            <Text style={styles.h2}>7. Questions &amp; Contact</Text>
                            <Text style={styles.paragraph}>
                                For questions regarding these Terms, please reach out via our <Link href="/contact" style={{ color: '#ec4899', textDecorationLine: 'underline' }}>Contact Page</Link>.
                            </Text>
                        </View>

                    </View>
                </View>
            </main>

            <WebFooter />
        </ScrollView>
    );
}

const styles = StyleSheet.create({
    scrollScreen: {
        flex: 1,
        backgroundColor: '#0a0b10',
    },
    scrollContent: {
        minHeight: '100%',
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'space-between',
    },
    container: {
        width: '100%',
        maxWidth: 860,
        paddingHorizontal: 20,
        paddingVertical: 40,
    },
    content: {
        width: '100%',
    },
    breadcrumb: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        marginBottom: 20,
    },
    breadcrumbLink: {
        color: '#94a3b8',
        fontSize: 13,
        textDecorationLine: 'none',
    },
    breadcrumbSeparator: {
        color: '#64748b',
        fontSize: 13,
    },
    breadcrumbCurrent: {
        color: '#f472b6',
        fontSize: 13,
        fontWeight: '600',
    },
    title: {
        fontSize: 34,
        fontWeight: '900',
        color: '#f8fafc',
        letterSpacing: -0.5,
        marginBottom: 8,
    },
    lastUpdated: {
        fontSize: 13,
        color: '#64748b',
        marginBottom: 24,
    },
    lead: {
        fontSize: 16,
        color: '#cbd5e1',
        lineHeight: 26,
        marginBottom: 32,
    },
    section: {
        marginBottom: 36,
    },
    h2: {
        fontSize: 20,
        fontWeight: '800',
        color: '#f8fafc',
        marginBottom: 12,
        letterSpacing: -0.2,
    },
    paragraph: {
        fontSize: 15,
        color: '#94a3b8',
        lineHeight: 25,
        marginBottom: 12,
    },
    bold: {
        fontWeight: '700',
        color: '#f8fafc',
    },
    alertBox: {
        backgroundColor: 'rgba(239, 68, 68, 0.08)',
        borderLeftWidth: 4,
        borderLeftColor: '#ef4444',
        borderRadius: 8,
        padding: 16,
        marginBottom: 14,
    },
    alertText: {
        fontSize: 14,
        color: '#fca5a5',
        lineHeight: 22,
    },
    bulletItem: {
        fontSize: 14,
        color: '#cbd5e1',
        lineHeight: 22,
        marginBottom: 8,
    },
});
